apiVersion: v1
kind: Secret
metadata:
  name: quiz-app-secrets
type: Opaque
data:
  secret-key: c3VwZXJzZWNyZXRrZXk=  # base64 encoded "supersecretkey"
  admin-password: YWRtaW4xMjM=        # base64 encoded "admin123" 