apiVersion: v1
kind: Service
metadata:
  name: quiz-app-service
  labels:
    app: quiz-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30080
    name: http
  selector:
    app: quiz-app 